### ISSUE TITLE
works too well :p

### ISSUE THREAD

**Issue by CarlFK** [jscher2000/move-active-tab-to-last-extension#1]
before adding this, I would often "move to end" so the 5-20 tabs I care about are to the right, and 100 tabs I might care about later are to the left.    then I can ^pgup/down over the tabs I care about and quickly find that other tab I'm working with.

I enabled move-active-tab-to-last-extension, now I don't need to "move to end" but now I cant ^pgup over the right 5 tabs as it keeps moving the 2nd tab to the end, and a bunch of ^pgup just keep moving the last 2 tabs to the end.

Can you add a parameter or something that helps define "active" to something less aggressive? 

Like maybe wait 30 seconds to decide the current tab is active.  

Or whatever is easy and maybe will work for me.

**Comment by jscher2000** [comment]
There is an API for scheduling things ([alarms](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/alarms)), but I had been procrastinating on learning how to use it. As of version 0.4, you can now set a delay of up to 30 seconds. Let me know how it works for you.

**Comment by CarlFK** [comment]
Neat - thank you!

A few hours of using it, no real complaints.

**Comment by jscher2000** [comment]
Sounds good, thanks.
