### ISSUE TITLE
add option to move the latest tab to the beginning

### ISSUE THREAD

**Issue by maxim-uvarov** [jscher2000/move-active-tab-to-last-extension#2]
Hi! Thank you for the extension! I'm migrating to Firefox from Chrome, where I had an extension with similar functionality for a long time.

Could you please consider adding an option to move the active tab to the beginning instead of the end, if it is technically possible? This way, pressing cmd+2 will always take a user to the previous active tab.

**Comment by jscher2000** [comment]
I think I can do this. 

If you want a keyboard shortcut to switch to the previous active tab *without moving it*, I do have a different add-on for that with a bunch of other features. I don't think it will let you use the default Firefox keyboard shortcut, though, so if you need that shortcut, you'll need to wait for this one to be updated (or find a different one).

Here's the other extension if you want to take a look: https://addons.mozilla.org/firefox/addon/switch-to-previous-active-tab/

**Comment by jscher2000** [comment]
A new version 0.5 with this feature is under review on the Add-ons site. Typically will be available within 24 hours.

**Comment by maxim-uvarov** [comment]
> A new version 0.5 with this feature is under review on the Add-ons site. Typically will be available within 24 hours.

@jscher2000, thank you so much for such a quick response!

**Comment by maxim-uvarov** [comment]
> If you want a keyboard shortcut to switch to the previous active tab without moving it, I

I prefer it when tabs are arranged based on their recency of use, with the most recently used tabs at the beginning. This way, the previous tab will always be 2, the tab before that will be 3, and so on. If the tabs are arranged at the end, I have to think about whether the previous tab will be 8, 7, or 6 in order to use the cmd+num shortcut.

Waiting for a publication on the Addons site 🙏

**Comment by jscher2000** [comment]
It is live now. Thanks for the suggestion.
